# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}

    - name: Validate YAML Schema
      uses: JKarwatka/validate-yaml-schema-action@0.2.0-alpha
      with:
        # List of files to validate along with corresponding schema
        files-to-validate: '[{ "path": "test/testcase1/testcase1.yaml", "schema": "test/testcase1/testcase1.schema.yaml" }]'
